import Link from "next/link";

export const metadata = {
  title: "Imprint & AI notice — Second Voice",
  description: "Operator information and AI transparency notice for Second Voice.",
};

const operatorName = process.env.SECOND_VOICE_LEGAL_NAME?.trim() || "Miguel Almeida";
const operatorAddress = process.env.SECOND_VOICE_LEGAL_ADDRESS?.trim() || "";
const contactEmail = process.env.SECOND_VOICE_LEGAL_EMAIL?.trim() || "";

export default function LegalPage() {
  const addressLines = operatorAddress
    ? operatorAddress.split(/\n|\|/).map((line) => line.trim()).filter(Boolean)
    : [];

  return (
    <main className="mx-auto max-w-2xl px-6 py-12 text-[#eeeae3] sm:py-16">
      <Link href="/second-voice" className="underline underline-offset-4">
        Back to Second Voice
      </Link>

      <section id="imprint" className="mt-10 space-y-4 leading-relaxed">
        <p className="text-xs uppercase tracking-[0.16em] text-[#8e8a84]">Imprint / Impressum</p>
        <h1 className="text-3xl">Service provider</h1>
        <div>
          <p>{operatorName}</p>
          {addressLines.length > 0 ? (
            <address className="not-italic">
              {addressLines.map((line) => <span key={line} className="block">{line}</span>)}
            </address>
          ) : (
            <p>Serviceable postal address not configured.</p>
          )}
        </div>
        <div>
          <p className="font-semibold">Contact</p>
          {contactEmail ? (
            <a href={`mailto:${contactEmail}`} className="break-words underline underline-offset-4">
              {contactEmail}
            </a>
          ) : (
            <p>Contact email not configured.</p>
          )}
        </div>
        <p className="text-sm text-[#aaa59e]">
          Provider information for this publicly accessible online service. See the separate privacy
          notice for information about personal-data processing.
        </p>
        <p>
          <Link href="/second-voice/privacy" className="underline underline-offset-4">
            Privacy & contact
          </Link>
        </p>
      </section>

      <section id="ai-notice" className="mt-12 space-y-4 border-t border-white/10 pt-10 leading-relaxed">
        <p className="text-xs uppercase tracking-[0.16em] text-[#8e8a84]">AI & author notice</p>
        <h2 className="text-2xl">Generated writing</h2>
        <p>
          Second Voice uses generative AI to create new text using broad stylistic traits associated
          with selected writers and writing outcomes. Outputs are generated by an AI system.
        </p>
        <p>
          Named authors are creative reference points only. Second Voice is independent and is not
          affiliated with, endorsed by, or approved by those authors, their estates, publishers, or
          representatives.
        </p>
        <p>
          Generated text can be inaccurate, unexpected, or resemble existing phrasing. Check the
          result before relying on or publishing it. You are responsible for having the right to
          submit the source material and for how you use the resulting text.
        </p>
        <p>
          Do not submit passwords, API keys, confidential material, sensitive personal data, or
          information you are not authorised to send to an AI provider.
        </p>
      </section>
    </main>
  );
}
